#define B_SCENE 0


#define B_ACCELERATION_STRUCTURE 0
#define B_PLIM_LOOK_UP 1
#define B_VERTICES 2
#define B_NORMALS 3
#define B_TEXCOORDS 4
#define B_INDICES 5
#define B_MATERIALS 6
#define B_MATRICES 7
#define B_TEXTURES 8
#define B_TANGENTS 9
#define B_COLORS 10

#define B_ALIAS_TABLE 0
#define B_POINT_LIGHTS 1
#define B_TRIANGLE_LIGHTS 2
#define B_ENVIRONMENTAL_MAP 3
#define B_ENVIRONMENTAL_ALIAS_MAP 4

#define B_FRAME_WORLD_POSITION 0
#define B_FRAME_ALBEDO 1
#define B_FRAME_NORMAL 2
#define B_FRAME_MATERIAL_PROPS 3
#define B_PERV_FRAME_WORLD_POSITION 4
#define B_PERV_FRAME_ALBEDO 5
#define B_PERV_FRAME_NORMAL 6
#define B_PREV_FRAME_MATERIAL_PROPS 7
#define B_RESERVIORS_INFO 8
#define B_RESERVIORS_WEIGHT 9
#define B_PREV_RESERVIORS_INFO 10 
#define B_PREV_RESERVIORS_WEIGHT 11
#define B_TMP_RESERVIORS_INFO 12
#define B_TMP_RESERVIORS_WEIGHT 13
#define B_STORAGE_IMAGE 14

